// Simple test of Sounio codegen without full MedLang compiler

// Simulate a simple IR for testing
use std::fmt::Write as FmtWrite;

#[derive(Debug, Clone)]
pub enum IRExpr {
    Literal(f64),
    Var(String),
    Binary(IRBinaryOp, Box<IRExpr>, Box<IRExpr>),
    Unary(IRUnaryOp, Box<IRExpr>),
    Call(String, Vec<IRExpr>),
    Index(Box<IRExpr>, Box<IRExpr>),
}

#[derive(Debug, Clone, Copy)]
pub enum IRBinaryOp {
    Add, Sub, Mul, Div, Pow,
}

#[derive(Debug, Clone, Copy)]
pub enum IRUnaryOp {
    Neg,
}

#[derive(Debug, Clone)]
pub struct IRStateVar {
    pub name: String,
    pub dimension: String,
    pub initial_value: Option<IRExpr>,
}

#[derive(Debug, Clone)]
pub struct IRParam {
    pub name: String,
    pub dimension: String,
}

#[derive(Debug, Clone)]
pub struct IRODEEquation {
    pub state_var: String,
    pub rhs: IRExpr,
}

#[derive(Debug, Clone)]
pub struct IRObservable {
    pub name: String,
    pub dimension: String,
    pub expr: IRExpr,
}

#[derive(Debug, Clone)]
pub struct IRModel {
    pub name: String,
    pub states: Vec<IRStateVar>,
    pub params: Vec<IRParam>,
    pub odes: Vec<IRODEEquation>,
    pub observables: Vec<IRObservable>,
}

#[derive(Debug, Clone)]
pub struct IRProgram {
    pub model: IRModel,
}

// Simplified Sounio codegen
fn generate_sounio_simple(ir: &IRProgram) -> Result<String, std::fmt::Error> {
    let mut output = String::new();

    writeln!(output, "//! Generated by MedLang → Sounio compiler")?;
    writeln!(output, "//! Model: {}", ir.model.name)?;
    writeln!(output)?;
    writeln!(output, "module {}", ir.model.name)?;
    writeln!(output)?;
    writeln!(output, "// Sounio standard library imports")?;
    writeln!(output, "import std.math.{{exp, log, sqrt}}")?;
    writeln!(output, "import std.effects.{{Mut, IO, Alloc}}")?;
    writeln!(output)?;

    // Simple ODE function
    writeln!(output, "fn ode_system(state: &State, params: &Params) -> StateDerivatives {{")?;
    for ode in &ir.model.odes {
        write!(output, "    // d{}/dt = ", ode.state_var)?;
        write_expr(&mut output, &ode.rhs)?;
        writeln!(output)?;
    }
    writeln!(output, "    StateDerivatives {{ /* ... */ }}")?;
    writeln!(output, "}}")?;
    writeln!(output)?;

    writeln!(output, "fn main() -> effect[IO] {{")?;
    writeln!(output, "    println!(\"PBPK Simulation: {}\")", ir.model.name)?;
    writeln!(output, "}}")?;

    Ok(output)
}

fn write_expr(output: &mut String, expr: &IRExpr) -> Result<(), std::fmt::Error> {
    match expr {
        IRExpr::Literal(v) => write!(output, "{}", v),
        IRExpr::Var(name) => write!(output, "{}", name),
        IRExpr::Binary(op, l, r) => {
            write!(output, "(")?;
            write_expr(output, l)?;
            match op {
                IRBinaryOp::Add => write!(output, " + ")?,
                IRBinaryOp::Sub => write!(output, " - ")?,
                IRBinaryOp::Mul => write!(output, " * ")?,
                IRBinaryOp::Div => write!(output, " / ")?,
                IRBinaryOp::Pow => write!(output, " ** ")?,
            }
            write_expr(output, r)?;
            write!(output, ")")
        }
        IRExpr::Call(func, args) => {
            write!(output, "{}(", func)?;
            for (i, arg) in args.iter().enumerate() {
                if i > 0 { write!(output, ", ")?; }
                write_expr(output, arg)?;
            }
            write!(output, ")")
        }
        _ => write!(output, "/* expr */"),
    }
}

fn main() {
    // Create a simple test model
    let ir = IRProgram {
        model: IRModel {
            name: "SimpleOralPK".to_string(),
            states: vec![
                IRStateVar {
                    name: "A_gut".to_string(),
                    dimension: "Mass".to_string(),
                    initial_value: Some(IRExpr::Literal(100.0)),
                },
                IRStateVar {
                    name: "C_plasma".to_string(),
                    dimension: "Concentration".to_string(),
                    initial_value: Some(IRExpr::Literal(0.0)),
                },
            ],
            params: vec![
                IRParam { name: "Ka".to_string(), dimension: "RateConst".to_string() },
                IRParam { name: "CL".to_string(), dimension: "Clearance".to_string() },
                IRParam { name: "V".to_string(), dimension: "Volume".to_string() },
            ],
            odes: vec![
                IRODEEquation {
                    state_var: "A_gut".to_string(),
                    rhs: IRExpr::Binary(
                        IRBinaryOp::Mul,
                        Box::new(IRExpr::Unary(IRUnaryOp::Neg, Box::new(IRExpr::Var("Ka".to_string())))),
                        Box::new(IRExpr::Var("A_gut".to_string())),
                    ),
                },
            ],
            observables: vec![
                IRObservable {
                    name: "C_plasma".to_string(),
                    dimension: "Concentration".to_string(),
                    expr: IRExpr::Binary(
                        IRBinaryOp::Div,
                        Box::new(IRExpr::Var("A_central".to_string())),
                        Box::new(IRExpr::Var("V".to_string())),
                    ),
                },
            ],
        },
    };

    match generate_sounio_simple(&ir) {
        Ok(code) => {
            println!("✓ Sounio code generated successfully!\n");
            println!("{}", code);
        }
        Err(e) => {
            eprintln!("✗ Code generation failed: {}", e);
        }
    }
}
