# =============================================================================
# MEDLANG-TO-DEMETRIOS COMPILER
# =============================================================================
# Transpiles MedLang DSL (domain-specific PBPK language) to Demetrios
# (novel L0 systems + scientific programming language)
#
# KEY INNOVATION:
# Demetrios provides compile-time dimensional analysis (units of measure)
# which catches unit errors that are a major source of bugs in PBPK modeling.
#
# Example transformation:
#   MedLang: CLint: 125.0 µL/min/mg
#   Demetrios: let CLint: uL_per_min_per_mg = 125.0
#
# The Demetrios compiler will reject:
#   let result: L_per_h = CLint  // Type error! Wrong units
#
# This catches errors like:
# - Forgetting to convert µL/min to L/h
# - Using mg instead of kg for body weight
# - Mixing concentration units (µM vs ng/mL)
#
# Darwin PBPK Platform v2.10.0
# Author: Dr. Demetrios Agourakis
# Date: November 2025
# =============================================================================

module MedLangDemetriosCompiler

export compile_medlang_to_demetrios, MedLangAST, DemetriosCode
export generate_demetrios_pbpk, generate_demetrios_ddi

# =============================================================================
# UNIT SYSTEM MAPPING
# =============================================================================

"""
Map MedLang units to Demetrios type-safe units.
Demetrios uses compile-time dimensional analysis.
"""
const UNIT_MAPPING = Dict{String, String}(
    # Concentrations
    "µM" => "uM",
    "μM" => "uM",
    "uM" => "uM",
    "nM" => "nM",
    "ng/mL" => "ng_per_mL",
    "mg/L" => "mg_per_L",
    "µg/mL" => "ug_per_mL",

    # Clearance
    "L/h" => "L_per_h",
    "mL/min" => "mL_per_min",
    "µL/min/mg" => "uL_per_min_per_mg",
    "mL/min/kg" => "mL_per_min_per_kg",

    # Volumes
    "L" => "L",
    "mL" => "mL",
    "L/kg" => "L_per_kg",

    # Mass
    "mg" => "mg",
    "kg" => "kg",
    "g" => "g",

    # Time
    "h" => "h",
    "min" => "min",
    "s" => "s",

    # Rate constants
    "1/h" => "per_h",
    "h⁻¹" => "per_h",
    "1/min" => "per_min",

    # Fractions (dimensionless)
    "" => "Real",
    "fraction" => "Real",
    "%" => "Percent",

    # Specialized PBPK units
    "pmol/min/mg" => "pmol_per_min_per_mg",
    "pmol/mg" => "pmol_per_mg",
)

"""
Demetrios unit type definitions (generated preamble).
"""
const DEMETRIOS_UNIT_TYPES = """
// =============================================================================
// DEMETRIOS UNIT TYPE DEFINITIONS FOR PBPK
// =============================================================================
// Compile-time dimensional analysis prevents unit errors
// Generated by Darwin PBPK Platform MedLang Compiler

// Base units
type mg = Mass<mg>
type g = Mass<g>
type kg = Mass<kg>
type L = Volume<L>
type mL = Volume<mL>
type h = Time<h>
type min = Time<min>
type s = Time<s>

// Concentration units
type uM = Amount<umol> / Volume<L>           // micromolar
type nM = Amount<nmol> / Volume<L>           // nanomolar
type ng_per_mL = Mass<ng> / Volume<mL>       // ng/mL
type mg_per_L = Mass<mg> / Volume<L>         // mg/L
type ug_per_mL = Mass<ug> / Volume<mL>       // µg/mL

// Clearance units
type L_per_h = Volume<L> / Time<h>           // L/h
type mL_per_min = Volume<mL> / Time<min>     // mL/min
type uL_per_min_per_mg = Volume<uL> / Time<min> / Mass<mg>  // intrinsic clearance
type mL_per_min_per_kg = Volume<mL> / Time<min> / Mass<kg>  // body weight normalized

// Volume distribution units
type L_per_kg = Volume<L> / Mass<kg>         // Vd normalized to body weight

// Rate constants
type per_h = 1 / Time<h>                     // h⁻¹
type per_min = 1 / Time<min>                 // min⁻¹

// Enzyme kinetics
type pmol_per_min_per_mg = Amount<pmol> / Time<min> / Mass<mg>  // Vmax
type pmol_per_mg = Amount<pmol> / Mass<mg>   // Enzyme abundance

// Fractions (dimensionless, but type-safe)
type Fraction = Real { 0.0 <= self <= 1.0 }  // Refinement type!
type Percent = Real { 0.0 <= self <= 100.0 }

// =============================================================================
// UNIT CONVERSION FUNCTIONS
// =============================================================================

/// Convert mL/min to L/h (common PBPK conversion)
fn mL_min_to_L_h(cl: mL_per_min) -> L_per_h {
    cl * 0.06  // mL/min × 60 min/h × 1 L/1000 mL = L/h × 0.06
}

/// Convert µL/min/mg to L/h (microsomal to whole liver)
fn CLint_to_CLh(
    clint: uL_per_min_per_mg,
    mppgl: pmol_per_mg,     // mg microsomal protein per g liver
    liver_weight: g         // liver weight
) -> L_per_h {
    clint * mppgl * liver_weight * 60.0 / 1_000_000.0
}

/// Convert µM to ng/mL given MW
fn uM_to_ng_mL(conc: uM, mw: g) -> ng_per_mL {
    conc * mw  // µM × g/mol = µg/L = ng/mL
}
"""

# =============================================================================
# MEDLANG AST STRUCTURES
# =============================================================================

"""
Abstract Syntax Tree node types for MedLang.
"""
abstract type MedLangNode end

struct MedLangModel <: MedLangNode
    name::String
    drug_name::String
    compartments::Vector{MedLangNode}
    parameters::Vector{MedLangNode}
    equations::Vector{MedLangNode}
    observables::Vector{MedLangNode}
end

struct MedLangParameter <: MedLangNode
    name::String
    value::Float64
    unit::String
    description::String
end

struct MedLangState <: MedLangNode
    name::String
    initial_value::Float64
    unit::String
end

struct MedLangODE <: MedLangNode
    state_name::String
    rhs::String  # Right-hand side expression
end

struct MedLangObservable <: MedLangNode
    name::String
    expression::String
    unit::String
end

struct MedLangDDI <: MedLangNode
    perpetrator::String
    victim::String
    mechanism::Symbol
    parameters::Dict{String, Float64}
end

# =============================================================================
# DEMETRIOS CODE GENERATION
# =============================================================================

"""
Container for generated Demetrios code.
"""
struct DemetriosCode
    preamble::String
    types::String
    parameters::String
    state::String
    functions::String
    effects::String
    main::String
end

"""
Convert MedLang unit string to Demetrios type.
"""
function medlang_unit_to_demetrios(unit::String)::String
    # Clean up the unit string
    unit_clean = strip(unit)

    # Direct mapping
    if haskey(UNIT_MAPPING, unit_clean)
        return UNIT_MAPPING[unit_clean]
    end

    # Try to construct compound unit
    # e.g., "mg/L" -> "mg_per_L"
    unit_demetrios = replace(unit_clean, "/" => "_per_")
    unit_demetrios = replace(unit_demetrios, " " => "_")
    unit_demetrios = replace(unit_demetrios, "µ" => "u")
    unit_demetrios = replace(unit_demetrios, "μ" => "u")
    unit_demetrios = replace(unit_demetrios, "⁻¹" => "")

    return unit_demetrios
end

"""
Generate Demetrios code for a PBPK model parameter.
"""
function generate_parameter(param::MedLangParameter)::String
    unit_type = medlang_unit_to_demetrios(param.unit)

    # Use refinement types for fractions
    if param.unit == "fraction" || (0.0 <= param.value <= 1.0 && param.unit == "")
        return """
    /// $(param.description)
    let $(param.name): Fraction = $(param.value)"""
    end

    return """
    /// $(param.description)
    let $(param.name): $(unit_type) = $(param.value)"""
end

"""
Generate Demetrios code for a state variable.
"""
function generate_state(state::MedLangState)::String
    unit_type = medlang_unit_to_demetrios(state.unit)

    return """
    /// State: $(state.name)
    var $(state.name): $(unit_type) = $(state.initial_value)"""
end

"""
Generate Demetrios ODE function.
"""
function generate_ode_function(equations::Vector{MedLangODE}, model_name::String)::String
    buf = IOBuffer()

    println(buf, """
/// ODE system for $(model_name)
/// Uses algebraic effects for safe mutation
fn ode_system(
    t: h,
    state: &mut PBPKState,
    params: &PBPKParams
) -> effect[Mut] {""")

    for eq in equations
        # Parse RHS and add type annotations
        rhs = eq.rhs
        println(buf, "    // d$(eq.state_name)/dt")
        println(buf, "    state.d_$(eq.state_name) = $(rhs)")
        println(buf)
    end

    println(buf, "}")

    return String(take!(buf))
end

"""
Generate Demetrios struct for PBPK parameters.
"""
function generate_params_struct(params::Vector{MedLangParameter})::String
    buf = IOBuffer()

    println(buf, """
/// PBPK model parameters with compile-time unit checking
struct PBPKParams {""")

    for param in params
        unit_type = medlang_unit_to_demetrios(param.unit)
        println(buf, "    $(param.name): $(unit_type),  // $(param.description)")
    end

    println(buf, "}")

    return String(take!(buf))
end

"""
Generate Demetrios struct for state variables.
"""
function generate_state_struct(states::Vector{MedLangState})::String
    buf = IOBuffer()

    println(buf, """
/// PBPK state variables (concentrations, amounts)
struct PBPKState {""")

    for state in states
        unit_type = medlang_unit_to_demetrios(state.unit)
        println(buf, "    $(state.name): $(unit_type),")
        println(buf, "    d_$(state.name): $(unit_type)_per_h,  // derivative")
    end

    println(buf, "}")

    return String(take!(buf))
end

# =============================================================================
# MAIN COMPILER FUNCTIONS
# =============================================================================

"""
Compile a complete MedLang model to Demetrios code.
"""
function compile_medlang_to_demetrios(model::MedLangModel)::DemetriosCode

    # Extract components
    params = filter(x -> x isa MedLangParameter, model.parameters)
    states = filter(x -> x isa MedLangState, model.compartments)
    equations = filter(x -> x isa MedLangODE, model.equations)
    observables = filter(x -> x isa MedLangObservable, model.observables)

    # Generate preamble
    preamble = """
// =============================================================================
// $(uppercase(model.name))
// =============================================================================
// Generated by Darwin PBPK Platform - MedLang to Demetrios Compiler
// Drug: $(model.drug_name)
//
// COMPILE-TIME SAFETY:
// - All units are type-checked at compile time
// - Unit mismatches cause compile errors, not runtime bugs
// - Refinement types ensure valid parameter ranges
// =============================================================================

import std.math.{exp, log, sqrt}
import std.effects.{Mut, IO, GPU}
import darwin.pbpk.{OdeSolver, Tsit5}
"""

    # Generate types
    types = DEMETRIOS_UNIT_TYPES

    # Generate parameters struct
    parameters = generate_params_struct(params)

    # Generate state struct
    state = generate_state_struct(states)

    # Generate ODE function
    functions = generate_ode_function(equations, model.name)

    # Generate effect handlers
    effects = """
/// Effect handler for ODE integration
effect OdeIntegration {
    fn step(dt: h) -> PBPKState
    fn observe(name: String) -> Real
}

/// Handler using Tsit5 (Runge-Kutta 5th order)
handler Tsit5Handler for OdeIntegration {
    fn step(dt: h) -> PBPKState {
        // Tsit5 adaptive step
        ode_system(self.t, &mut self.state, &self.params)
        self.t += dt
        self.state
    }
}
"""

    # Generate main simulation function
    main = """
/// Main PBPK simulation
/// Returns concentration-time profile
fn simulate_pbpk(
    params: PBPKParams,
    dose: mg,
    t_max: h,
    dt: h
) -> effect[IO, Mut] Vec<(h, uM)> {

    // Initialize state
    var state = PBPKState::new()
    state.A_gut = dose  // Oral dose in gut

    // Time course storage
    var results: Vec<(h, uM)> = Vec::new()

    // Integration loop with algebraic effects
    var t: h = 0.0

    while t <= t_max {
        // Record plasma concentration
        results.push((t, state.C_plasma))

        // ODE step (uses Tsit5Handler effect)
        with Tsit5Handler {
            state = step(dt)
        }

        t += dt
    }

    results
}

/// Entry point
fn main() -> effect[IO] {
    // Example: Midazolam PBPK simulation
    let params = PBPKParams {
        ka: 1.5,          // h⁻¹
        Fg: 0.57,         // fraction
        Fh: 0.77,         // fraction
        Vc: 30.0,         // L
        Vp: 50.0,         // L
        Q: 25.0,          // L/h
        CL: 25.0,         // L/h
    }

    let dose: mg = 7.5
    let results = simulate_pbpk(params, dose, 24.0, 0.1)

    // Print results
    for (t, c) in results {
        println!("t={t:.1} h, Cp={c:.3} µM")
    }
}
"""

    return DemetriosCode(preamble, types, parameters, state, functions, effects, main)
end

"""
Generate complete Demetrios source file.
"""
function generate_demetrios_source(code::DemetriosCode)::String
    return """
$(code.preamble)

$(code.types)

$(code.parameters)

$(code.state)

$(code.functions)

$(code.effects)

$(code.main)
"""
end

# =============================================================================
# DDI-SPECIFIC CODE GENERATION
# =============================================================================

"""
Generate Demetrios code for DDI prediction with type-safe units.
"""
function generate_demetrios_ddi(
    perpetrator::String,
    victim::String,
    mechanism::Symbol,
    Ki_uM::Float64,
    fm::Float64;
    kinact_h::Float64 = 0.0,
    KI_uM::Float64 = 0.0
)::String

    mech_str = if mechanism == :reversible
        "Reversible competitive inhibition"
    elseif mechanism == :mbi
        "Mechanism-based inactivation"
    elseif mechanism == :induction
        "Enzyme induction"
    else
        "Mixed mechanism"
    end

    return """
// =============================================================================
// DDI PREDICTION: $(uppercase(perpetrator)) + $(uppercase(victim))
// =============================================================================
// Mechanism: $(mech_str)
// Generated by Darwin PBPK Platform
//
// UNIT SAFETY: All parameters are type-checked at compile time
// =============================================================================

import darwin.ddi.{predict_auc_ratio, DDIMechanism}

/// DDI parameters with compile-time unit verification
struct DDIParams {
    Ki: uM,                    // Inhibition constant
    fm: Fraction,              // Fraction metabolized (0-1)
    $(mechanism == :mbi ? "kinact: per_h,             // MBI inactivation rate\n    KI: uM,                    // MBI concentration for half-max" : "")
}

/// Calculate AUC ratio with type-safe units
/// Compile error if units don't match!
fn calculate_auc_ratio(
    I: uM,                     // Inhibitor concentration (unbound)
    params: &DDIParams
) -> Real {
    $(if mechanism == :reversible
        """
    // Reversible inhibition: R = 1 + [I]/Ki
    let R: Real = 1.0 + I / params.Ki

    // AUC ratio = 1 / (fm/R + (1-fm))
    1.0 / (params.fm / R + (1.0 - params.fm))"""
    elseif mechanism == :mbi
        """
    // MBI: λ = kinact × [I] / (KI + [I])
    let lambda: per_h = params.kinact * I / (params.KI + I)

    // Steady-state enzyme fraction
    let kdeg: per_h = 0.019  // CYP3A4 degradation rate
    let E_ss: Fraction = kdeg / (kdeg + lambda)

    // AUC ratio = 1 / (fm × E_ss + (1-fm))
    1.0 / (params.fm * E_ss + (1.0 - params.fm))"""
    else
        "1.0  // Unknown mechanism"
    end)
}

/// Example usage
fn main() -> effect[IO] {
    let params = DDIParams {
        Ki: $(Ki_uM),        // µM
        fm: $(fm),           // fraction
        $(mechanism == :mbi ? "kinact: $(kinact_h),     // h⁻¹\n        KI: $(KI_uM),          // µM" : "")
    }

    // Clinical concentration (unbound)
    let I_clinical: uM = 10.0

    let auc_ratio = calculate_auc_ratio(I_clinical, &params)

    println!("$(perpetrator) + $(victim)")
    println!("Predicted AUC ratio: {auc_ratio:.1}x")

    // TYPE SAFETY DEMONSTRATION:
    // The following would cause a COMPILE ERROR:
    // let wrong: ng_per_mL = I_clinical  // Error! uM != ng_per_mL
    // let wrong_ratio = calculate_auc_ratio(10.0, &params)  // Error! Real != uM
}
"""
end

"""
Generate Demetrios code for a complete PBPK model with DDI.
"""
function generate_demetrios_pbpk(
    drug_name::String;
    MW::Float64 = 300.0,
    ka::Float64 = 1.0,
    F::Float64 = 0.5,
    Vc::Float64 = 30.0,
    Vp::Float64 = 50.0,
    CL::Float64 = 10.0,
    Q::Float64 = 20.0
)::String

    return """
// =============================================================================
// PBPK MODEL: $(uppercase(drug_name))
// =============================================================================
// Two-compartment oral PK model with first-pass metabolism
// Generated by Darwin PBPK Platform
//
// COMPILE-TIME UNIT SAFETY:
// - All parameters have explicit unit types
// - Unit conversions are verified at compile time
// - Prevents common PBPK bugs (e.g., mL/min vs L/h confusion)
// =============================================================================

import std.math.{exp, log}
import std.effects.{Mut, IO}
import darwin.ode.{solve, Tsit5, ODEProblem}

// =============================================================================
// UNIT TYPE DEFINITIONS
// =============================================================================

type mg = Mass<mg>
type kg = Mass<kg>
type L = Volume<L>
type h = Time<h>
type uM = Amount<umol> / Volume<L>
type L_per_h = Volume<L> / Time<h>
type per_h = 1 / Time<h>
type Fraction = Real { 0.0 <= self <= 1.0 }

// =============================================================================
// MODEL PARAMETERS
// =============================================================================

/// Drug-specific parameters with compile-time unit verification
struct DrugParams {
    name: String,
    MW: Real,                  // g/mol (molecular weight)
    ka: per_h,                 // Absorption rate constant
    F: Fraction,               // Bioavailability
    Fg: Fraction,              // Gut bioavailability
    Fh: Fraction,              // Hepatic bioavailability
    Vc: L,                     // Central volume
    Vp: L,                     // Peripheral volume
    CL: L_per_h,               // Total clearance
    Q: L_per_h,                // Intercompartmental clearance
}

/// Patient-specific parameters
struct PatientParams {
    weight: kg,
    age: Real,                 // years
    sex: String,
    GFR: L_per_h,              // Glomerular filtration rate
}

// =============================================================================
// STATE VARIABLES
// =============================================================================

/// PK state with explicit units
struct PKState {
    A_gut: mg,                 // Amount in gut lumen
    C_central: uM,             // Central concentration
    A_periph: mg,              // Amount in peripheral
    t: h,                      // Current time
}

impl PKState {
    fn new() -> Self {
        PKState {
            A_gut: 0.0,
            C_central: 0.0,
            A_periph: 0.0,
            t: 0.0,
        }
    }
}

// =============================================================================
// ODE SYSTEM
// =============================================================================

/// Two-compartment oral PK model
/// All unit conversions verified at compile time!
fn pk_ode(
    state: &PKState,
    params: &DrugParams
) -> effect[Mut] PKDerivatives {

    // Gut compartment: dA_gut/dt = -ka × A_gut
    let dA_gut: mg_per_h = -params.ka * state.A_gut

    // Absorption rate (amount per time)
    let absorption: mg_per_h = params.ka * state.A_gut * params.F

    // Convert absorption to concentration change
    // dC/dt = (absorption/MW/Vc) - (CL/Vc)×C - (Q/Vc)×(C - Cp)
    let C_periph: uM = (state.A_periph / params.MW) / params.Vp * 1000.0

    let dC_central: uM_per_h = (
        absorption / params.MW / params.Vc * 1000.0  // Absorption
        - params.CL / params.Vc * state.C_central     // Elimination
        - params.Q / params.Vc * (state.C_central - C_periph)  // Distribution
    )

    // Peripheral compartment
    let dA_periph: mg_per_h = params.Q * (state.C_central - C_periph) * params.Vc * params.MW / 1000.0

    PKDerivatives {
        dA_gut,
        dC_central,
        dA_periph,
    }
}

// =============================================================================
// SIMULATION FUNCTION
// =============================================================================

/// Simulate PK profile
/// Returns vector of (time, concentration) pairs
fn simulate(
    params: DrugParams,
    dose: mg,
    t_max: h,
    dt: h
) -> effect[IO, Mut] Vec<(h, uM)> {

    // Initialize state
    var state = PKState::new()
    state.A_gut = dose  // Oral dose

    // Results storage
    var results: Vec<(h, uM)> = Vec::new()

    // Integration loop
    while state.t <= t_max {
        // Store current state
        results.push((state.t, state.C_central))

        // Calculate derivatives
        let derivs = pk_ode(&state, &params)

        // Euler step (use Tsit5 for production)
        state.A_gut += derivs.dA_gut * dt
        state.C_central += derivs.dC_central * dt
        state.A_periph += derivs.dA_periph * dt
        state.t += dt

        // Ensure non-negative
        state.A_gut = max(state.A_gut, 0.0)
        state.C_central = max(state.C_central, 0.0)
        state.A_periph = max(state.A_periph, 0.0)
    }

    results
}

// =============================================================================
// PK METRICS CALCULATION
// =============================================================================

/// Calculate AUC using trapezoidal rule
/// Note: Input and output types are explicit
fn calculate_auc(profile: &Vec<(h, uM)>) -> uM_h {
    var auc: uM_h = 0.0

    for i in 1..profile.len() {
        let (t1, c1) = profile[i-1]
        let (t2, c2) = profile[i]
        let dt: h = t2 - t1

        // Trapezoidal: (c1 + c2) / 2 × dt
        auc += (c1 + c2) / 2.0 * dt
    }

    auc
}

/// Find Cmax and Tmax
fn find_cmax(profile: &Vec<(h, uM)>) -> (uM, h) {
    var cmax: uM = 0.0
    var tmax: h = 0.0

    for (t, c) in profile {
        if c > cmax {
            cmax = c
            tmax = t
        }
    }

    (cmax, tmax)
}

// =============================================================================
// MAIN ENTRY POINT
// =============================================================================

fn main() -> effect[IO] {
    // $(drug_name) parameters
    let params = DrugParams {
        name: "$(drug_name)",
        MW: $(MW),
        ka: $(ka),
        F: $(F),
        Fg: $(F^0.5),   // Approximate
        Fh: $(F^0.5),   // Approximate
        Vc: $(Vc),
        Vp: $(Vp),
        CL: $(CL),
        Q: $(Q),
    }

    // Simulate single dose
    let dose: mg = 100.0
    let results = simulate(params, dose, 24.0, 0.1)

    // Calculate metrics
    let auc = calculate_auc(&results)
    let (cmax, tmax) = find_cmax(&results)

    // Print results
    println!("=== $(drug_name) PK Simulation ===")
    println!("Dose: {dose} mg")
    println!("AUC(0-24h): {auc:.1} µM·h")
    println!("Cmax: {cmax:.2} µM")
    println!("Tmax: {tmax:.1} h")

    // COMPILE-TIME TYPE SAFETY EXAMPLES:
    // These would cause compile errors:
    // let wrong: L = auc           // Error! uM_h != L
    // let wrong: mg = cmax         // Error! uM != mg
    // let wrong = auc + dose       // Error! Can't add uM_h + mg
}
"""
end

# =============================================================================
# EXPORTS
# =============================================================================

export compile_medlang_to_demetrios, generate_demetrios_source
export generate_demetrios_ddi, generate_demetrios_pbpk
export MedLangModel, MedLangParameter, MedLangState, MedLangODE, MedLangObservable
export DemetriosCode, UNIT_MAPPING

end # module
